version: '3.8'

services:
  app:
    build: .
    container_name: scheduler_app
    restart: unless-stopped
    ports:
      - "3100:3000"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 50M